### ISSUE TITLE
2FA - Not working with Google Authenticator 

### ISSUE THREAD

**Issue by Anish-Agnihotri** [via-platform/via#3]
Attempting to add two factor authentication to my account through Google Authenticator. Does not allow me to verify the authorization code and continue past the screen (unless I decide to ignore the 2FA all together). 

System specifications: 
`Operating System: macOS High Sierra 10.13
  RAM: 10GB
  Network: Same network as device being authenticated upon`

Authenticator specifications:
`Phone: iPhone 6 16GB - iOS 11.1.2`

Error video: [Imgur Link, it's a gif - just wait a few seconds.](https://i.imgur.com/tRh0QtE.gif)

Thanks, keep up the good work!

**Comment by DakotaG** [comment]
Should probably also add an actual error message.
